"""End-to-end tests for RAG features using fixture documents with known content.

Fixture documents live in tests/fixtures/ and are generated by
tests/fixtures/create_test_docs.py.  Each test asserts concrete output
values derived from the known input content.
"""

import os
import re
import pytest
from pathlib import Path

from doc2mark.core.chunker import Chunk, ChunkingConfig, chunk_content


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FIXTURES = Path(__file__).parent / "fixtures"


def _load(filename, **kwargs):
    """Load a fixture document."""
    path = FIXTURES / filename
    if not path.exists():
        pytest.skip(f"{filename} not found — run tests/fixtures/create_test_docs.py")
    old_key = os.environ.get("OPENAI_API_KEY")
    if not old_key:
        os.environ["OPENAI_API_KEY"] = "sk-test-dummy-not-used"
    try:
        from doc2mark import UnifiedDocumentLoader
        loader = UnifiedDocumentLoader()
        return loader.load(str(path), extract_images=False, ocr_images=False, **kwargs)
    finally:
        if not old_key:
            del os.environ["OPENAI_API_KEY"]


# ===================================================================
# DOCX — page breaks, headers/footers, footnotes, content fidelity
# ===================================================================

class TestDocxPageBreaks:
    """DOCX with explicit <w:br w:type='page'/> should have page tracking."""

    def test_three_pages_detected(self):
        result = _load("test_rag_features.docx")
        pages = {item.get("page") for item in result.json_content if item.get("page") is not None}
        assert pages == {1, 2, 3}, f"Expected pages {{1,2,3}}, got {pages}"

    def test_page_markers_in_markdown(self):
        result = _load("test_rag_features.docx")
        markers = re.findall(r"<!-- page (\d+) -->", result.content)
        assert markers == ["1", "2", "3"]

    def test_introduction_on_page_1(self):
        result = _load("test_rag_features.docx")
        page1_items = [i for i in result.json_content if i.get("page") == 1]
        titles = [i["content"] for i in page1_items if i["type"] == "text:title"]
        assert "Introduction" in titles

    def test_methodology_on_page_2(self):
        result = _load("test_rag_features.docx")
        page2_items = [i for i in result.json_content if i.get("page") == 2]
        titles = [i["content"] for i in page2_items if i["type"] == "text:title"]
        assert "Methodology" in titles

    def test_results_on_page_3(self):
        result = _load("test_rag_features.docx")
        page3_items = [i for i in result.json_content if i.get("page") == 3]
        titles = [i["content"] for i in page3_items if i["type"] == "text:title"]
        assert "Results" in titles


class TestDocxHeaderFooter:
    """DOCX headers/footers should be tagged and excluded from body."""

    def test_header_tagged(self):
        result = _load("test_rag_features.docx")
        headers = [i for i in result.json_content if i["type"] == "text:header"]
        assert len(headers) >= 1
        assert any("ACME" in h["content"] or "Confidential" in h["content"] for h in headers)

    def test_footer_tagged(self):
        result = _load("test_rag_features.docx")
        footers = [i for i in result.json_content if i["type"] == "text:footer"]
        assert len(footers) >= 1

    def test_header_not_in_markdown_body(self):
        result = _load("test_rag_features.docx")
        # Headers are in json_content but NOT in the main markdown output
        header_texts = [i["content"] for i in result.json_content if i["type"] == "text:header"]
        for header_text in header_texts:
            if header_text.strip():
                # The exact header text should not appear as a standalone line in markdown
                # (it may appear as part of footnote definitions, which is fine)
                lines = result.content.split("\n")
                normal_lines = [l for l in lines if not l.startswith("[^") and "<!-- " not in l]
                for line in normal_lines:
                    assert header_text not in line, f"Header '{header_text}' found in markdown body"


class TestDocxFootnotes:
    """DOCX footnotes should produce [^N] markers and definitions."""

    def test_footnote_reference_in_text(self):
        result = _load("test_rag_features.docx")
        # The first paragraph should have [^1]
        page1_normal = [i for i in result.json_content
                        if i.get("page") == 1 and i["type"] == "text:normal"]
        assert any("[^1]" in i["content"] for i in page1_normal), \
            "Expected [^1] reference in page 1 text"

    def test_footnote_definition_present(self):
        result = _load("test_rag_features.docx")
        footnotes = [i for i in result.json_content if i["type"] == "text:footnote"]
        assert len(footnotes) >= 1
        fn_texts = [f["content"] for f in footnotes]
        assert any("[^1]:" in t for t in fn_texts), "Expected [^1]: definition"

    def test_footnote_in_markdown_output(self):
        result = _load("test_rag_features.docx")
        assert "[^1]:" in result.content, "Footnote definition should appear in markdown"

    def test_endnote_distinct_from_footnote(self):
        """Endnotes should have 'en' prefix to avoid id collision with footnotes."""
        result = _load("test_rag_features.docx")
        footnotes = [i for i in result.json_content if i["type"] == "text:footnote"]
        ids = [re.match(r"\[\^(\w+)\]:", f["content"]).group(1)
               for f in footnotes if re.match(r"\[\^(\w+)\]:", f["content"])]
        # Should have both "1" (footnote) and "en1" (endnote)
        assert "1" in ids, f"Missing footnote id '1', got {ids}"
        assert "en1" in ids, f"Missing endnote id 'en1', got {ids}"


class TestDocxTableOnPage:
    """Tables should carry the correct page number."""

    def test_table_on_page_3(self):
        result = _load("test_rag_features.docx")
        tables = [i for i in result.json_content if i["type"] == "table"]
        assert len(tables) >= 1
        assert tables[0].get("page") == 3, f"Table should be on page 3, got {tables[0].get('page')}"

    def test_table_content_intact(self):
        result = _load("test_rag_features.docx")
        tables = [i for i in result.json_content if i["type"] == "table"]
        assert any("Accuracy" in t["content"] and "95.2%" in t["content"] for t in tables)


class TestDocxContentFidelity:
    """Page markers should not alter the actual text content."""

    def test_all_body_text_preserved(self):
        result = _load("test_rag_features.docx")
        expected_phrases = [
            "first paragraph on page one",
            "methodology section begins on page two",
            "novel approach combining X and Y",
            "Results are presented in the table below",
            "the approach works well",
        ]
        for phrase in expected_phrases:
            assert phrase in result.content, f"Missing: '{phrase}'"


# ===================================================================
# PDF — repeated header/footer dedup, footnotes, page markers
# ===================================================================

class TestPDFHeaderFooterDedup:
    """PDF with repeated header/footer on every page should dedup them."""

    def test_header_detected_on_all_pages(self):
        result = _load("test_rag_features.pdf")
        headers = [i for i in result.json_content if i["type"] == "text:header"]
        header_pages = {h.get("page") for h in headers}
        assert len(header_pages) == 5, f"Expected headers on 5 pages, got {header_pages}"

    def test_footer_detected_on_all_pages(self):
        result = _load("test_rag_features.pdf")
        footers = [i for i in result.json_content if i["type"] == "text:footer"]
        footer_pages = {f.get("page") for f in footers}
        assert len(footer_pages) == 5, f"Expected footers on 5 pages, got {footer_pages}"

    def test_header_excluded_from_markdown(self):
        result = _load("test_rag_features.pdf")
        assert "ACME Corp" not in result.content, "Header should be excluded from markdown"

    def test_footer_excluded_from_markdown(self):
        result = _load("test_rag_features.pdf")
        assert "Confidential" not in result.content, "Footer should be excluded from markdown"

    def test_body_content_preserved(self):
        result = _load("test_rag_features.pdf")
        expected = [
            "Revenue grew by 15%",
            "total addressable market",
            "Three major features",
            "Total revenue",
        ]
        for phrase in expected:
            assert phrase in result.content, f"Missing body text: '{phrase}'"

    def test_all_items_preserved_in_json(self):
        """Dedup retypes but never removes items from json_content."""
        result = _load("test_rag_features.pdf")
        total_items = len(result.json_content)
        # 5 pages × (header + body lines + maybe footnote + footer) → at least 25 items
        assert total_items >= 25, f"Expected ≥25 items, got {total_items}"


class TestPDFPageMarkers:
    """PDF should have page markers in markdown output."""

    def test_page_markers_present(self):
        result = _load("test_rag_features.pdf")
        markers = re.findall(r"<!-- page (\d+) -->", result.content)
        assert len(markers) >= 4, f"Expected ≥4 page markers, got {markers}"

    def test_page_markers_sequential(self):
        result = _load("test_rag_features.pdf")
        markers = [int(m) for m in re.findall(r"<!-- page (\d+) -->", result.content)]
        for i in range(1, len(markers)):
            assert markers[i] > markers[i - 1], f"Non-sequential: {markers}"


class TestPDFFootnotes:
    """PDF footnotes (small text at page bottom) should be classified correctly."""

    def test_footnotes_detected(self):
        result = _load("test_rag_features.pdf")
        footnotes = [i for i in result.json_content if i["type"] == "text:footnote"]
        assert len(footnotes) == 3, f"Expected 3 footnotes, got {len(footnotes)}"

    def test_footnote_pages(self):
        result = _load("test_rag_features.pdf")
        footnotes = [i for i in result.json_content if i["type"] == "text:footnote"]
        fn_pages = sorted(f.get("page") for f in footnotes)
        assert fn_pages == [1, 2, 4], f"Footnotes on wrong pages: {fn_pages}"

    def test_footnote_formatted_in_markdown(self):
        result = _load("test_rag_features.pdf")
        # Footnote "1. Source:..." should become "[^1]: Source:..."
        assert "[^1]:" in result.content, "Expected [^1]: format for footnote 1"
        assert "[^2]:" in result.content, "Expected [^2]: format for footnote 2"
        assert "[^3]:" in result.content, "Expected [^3]: format for footnote 3"

    def test_non_footnote_not_misclassified(self):
        """Body text that starts with a number should NOT be classified as footnote."""
        result = _load("test_rag_features.pdf")
        normal_items = [i for i in result.json_content
                        if i["type"] == "text:normal" and i.get("page") == 4]
        # "Total revenue: $12.5M" should be text:normal, not text:footnote
        body_texts = [i["content"] for i in normal_items]
        assert any("Total revenue" in t for t in body_texts), \
            "Body text 'Total revenue' should remain text:normal"


# ===================================================================
# XLSX — sheet markers
# ===================================================================

class TestXLSXSheetMarkers:
    """XLSX with multiple sheets should have sheet markers."""

    def test_sheet_markers_present(self):
        result = _load("test_rag_features.xlsx")
        markers = re.findall(r"<!-- sheet (\d+) -->", result.content)
        assert len(markers) == 2, f"Expected 2 sheet markers, got {markers}"

    def test_sheet_names_present(self):
        result = _load("test_rag_features.xlsx")
        assert "Sales Data" in result.content
        assert "Expenses" in result.content

    def test_uses_sheet_label_not_page(self):
        result = _load("test_rag_features.xlsx")
        assert "<!-- page " not in result.content
        assert "<!-- sheet " in result.content

    def test_table_data_intact(self):
        result = _load("test_rag_features.xlsx")
        assert "Widget A" in result.content
        assert "1200" in result.content
        assert "Salaries" in result.content


# ===================================================================
# PPTX — slide markers
# ===================================================================

class TestPPTXSlideMarkers:
    """PPTX with multiple slides should have slide markers."""

    def test_slide_markers_present(self):
        result = _load("test_rag_features.pptx")
        markers = re.findall(r"<!-- slide (\d+) -->", result.content)
        assert len(markers) == 3, f"Expected 3 slide markers, got {markers}"

    def test_uses_slide_label_not_page(self):
        result = _load("test_rag_features.pptx")
        assert "<!-- page " not in result.content
        assert "<!-- slide " in result.content

    def test_slide_content_present(self):
        result = _load("test_rag_features.pptx")
        assert "Quarterly Business Review" in result.content
        assert "Revenue Overview" in result.content
        assert "Key Metrics" in result.content


# ===================================================================
# Chunking — with real documents
# ===================================================================

class TestChunkingE2E:
    """Chunking real documents should produce meaningful chunks."""

    def test_pdf_chunks_have_page_ranges(self):
        result = _load("test_rag_features.pdf")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=500, overlap=0))
        assert len(chunks) >= 2, "Multi-page PDF should produce multiple chunks"
        for chunk in chunks:
            if chunk.page_start is not None:
                assert chunk.page_start >= 1
                assert chunk.page_end >= chunk.page_start

    def test_pdf_chunks_cover_all_content(self):
        result = _load("test_rag_features.pdf")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=500, overlap=0))
        all_text = " ".join(c.content for c in chunks)
        assert "Executive Summary" in all_text
        assert "Market Analysis" in all_text
        assert "Revenue grew" in all_text

    def test_pdf_headers_excluded_from_chunks(self):
        result = _load("test_rag_features.pdf")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=10000, overlap=0))
        all_text = " ".join(c.content for c in chunks)
        assert "ACME Corp" not in all_text, "Header should not appear in chunks"

    def test_docx_chunks_have_sections(self):
        result = _load("test_rag_features.docx")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=500, overlap=0))
        titles = [c.section_title for c in chunks if c.section_title]
        assert "Introduction" in titles
        assert "Methodology" in titles

    def test_docx_footnote_travels_with_chunk(self):
        result = _load("test_rag_features.docx")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=10000, overlap=0))
        # The chunk containing [^1] reference should also have [^1]: definition
        for chunk in chunks:
            if "[^1]" in chunk.content and "[^1]:" not in chunk.content.split("[^1]")[0]:
                # This chunk references footnote 1
                assert "[^1]:" in chunk.content, \
                    "Footnote definition should be in same chunk as reference"
                break

    def test_xlsx_chunks_contain_table_data(self):
        result = _load("test_rag_features.xlsx")
        chunks = result.get_chunks()
        all_text = " ".join(c.content for c in chunks)
        assert "Widget A" in all_text

    def test_chunk_indices_sequential(self):
        result = _load("test_rag_features.pdf")
        chunks = result.get_chunks(ChunkingConfig(max_chunk_size=300, overlap=0))
        for i, chunk in enumerate(chunks):
            assert chunk.chunk_index == i


# ===================================================================
# Content fidelity — markers don't corrupt content
# ===================================================================

# ===================================================================
# Real-world DOCX — fail-1.docx regression test
# ===================================================================

class TestFailDocx:
    """Regression tests for user-reported fail-1.docx."""

    @pytest.fixture
    def fail_docx(self, sample_documents_dir):
        path = sample_documents_dir / "fail-1.docx"
        if not path.exists():
            pytest.skip("fail-1.docx not found")
        return path

    def test_no_crash(self, fail_docx):
        old_key = os.environ.get("OPENAI_API_KEY")
        if not old_key:
            os.environ["OPENAI_API_KEY"] = "sk-test-dummy-not-used"
        try:
            from doc2mark import UnifiedDocumentLoader
            loader = UnifiedDocumentLoader()
            result = loader.load(str(fail_docx), extract_images=False, ocr_images=False)
            assert result.content
            assert len(result.content) > 100
        finally:
            if not old_key:
                del os.environ["OPENAI_API_KEY"]

    def test_pages_sequential(self, fail_docx):
        old_key = os.environ.get("OPENAI_API_KEY")
        if not old_key:
            os.environ["OPENAI_API_KEY"] = "sk-test-dummy-not-used"
        try:
            from doc2mark import UnifiedDocumentLoader
            loader = UnifiedDocumentLoader()
            result = loader.load(str(fail_docx), extract_images=False, ocr_images=False)
            pages = sorted({item.get("page") for item in result.json_content if item.get("page") is not None})
            # Pages should be sequential with no gaps
            for i in range(1, len(pages)):
                assert pages[i] == pages[i - 1] + 1, f"Page gap: {pages[i-1]} -> {pages[i]}"
            assert pages[0] == 1
        finally:
            if not old_key:
                del os.environ["OPENAI_API_KEY"]

    def test_multiple_pages_detected(self, fail_docx):
        """fail-1.docx has section breaks; should detect >1 page."""
        old_key = os.environ.get("OPENAI_API_KEY")
        if not old_key:
            os.environ["OPENAI_API_KEY"] = "sk-test-dummy-not-used"
        try:
            from doc2mark import UnifiedDocumentLoader
            loader = UnifiedDocumentLoader()
            result = loader.load(str(fail_docx), extract_images=False, ocr_images=False)
            pages = {item.get("page") for item in result.json_content if item.get("page") is not None}
            assert len(pages) > 5, f"Expected >5 pages, got {len(pages)}"
        finally:
            if not old_key:
                del os.environ["OPENAI_API_KEY"]

    def test_chunking_works(self, fail_docx):
        old_key = os.environ.get("OPENAI_API_KEY")
        if not old_key:
            os.environ["OPENAI_API_KEY"] = "sk-test-dummy-not-used"
        try:
            from doc2mark import UnifiedDocumentLoader, ChunkingConfig
            loader = UnifiedDocumentLoader()
            result = loader.load(str(fail_docx), extract_images=False, ocr_images=False)
            chunks = result.get_chunks(ChunkingConfig(max_chunk_size=1000, overlap=100))
            assert len(chunks) >= 5
            for chunk in chunks:
                assert chunk.content
                assert chunk.chunk_index >= 0
        finally:
            if not old_key:
                del os.environ["OPENAI_API_KEY"]


class TestContentFidelity:
    """Page/slide/sheet markers should not alter document text."""

    def test_pdf_no_marker_inside_paragraph(self):
        result = _load("test_rag_features.pdf")
        # Markers should be on their own lines, not inside paragraphs
        for line in result.content.split("\n"):
            if "<!--" in line:
                stripped = line.strip()
                assert stripped.startswith("<!--") and stripped.endswith("-->"), \
                    f"Marker should be standalone: '{stripped}'"

    def test_docx_markdown_parseable(self):
        """Output should be valid markdown (no broken syntax)."""
        result = _load("test_rag_features.docx")
        # Check heading syntax
        for line in result.content.split("\n"):
            if line.startswith("#"):
                assert re.match(r'^#{1,6}\s', line), f"Invalid heading: '{line}'"

    def test_pptx_content_not_duplicated(self):
        """Slide content should not be duplicated across slides."""
        result = _load("test_rag_features.pptx")
        count = result.content.count("Quarterly Business Review")
        assert count == 1, f"Title duplicated {count} times"
