name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (core + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all,dev]
      
      - name: Run unit tests (no OCR external API)
        env:
          # Ensure no accidental OpenAI calls in CI
          OPENAI_API_KEY: ""
        run: |
          python -m pytest -m "not integration and not requires_api_key" -q

  test-ocr:
    name: OCR tests (OpenAI)
    runs-on: ubuntu-latest
    needs: test
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (with OCR extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,ocr]

      - name: Run OCR-related tests
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          python -m pytest -m "requires_api_key" -q

      - name: Skip OCR tests (no OPENAI_API_KEY)
        if: ${{ env.OPENAI_API_KEY == '' }}
        run: |
          echo "Skipping OCR tests: OPENAI_API_KEY not set in repository secrets"

      - name: Upload coverage (optional)
        if: always()
        run: |
          echo "Coverage upload step placeholder"


